services:
  eventstore.db:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=True
      - EVENTSTORE_DB=/var/lib/eventstore-data
      - EVENTSTORE_INDEX=/var/lib/eventstore-index
      - EVENTSTORE_LOG=/var/log/eventstore
      - EVENTSTORE_REPLICATION_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=True
    ports:
      - "1113:1113"
      - "2113:2113"
    volumes:
        - ./eventstore-volume-data:/var/lib/eventstore-data
        - ./eventstore-volume-index:/var/lib/eventstore-index
        - ./eventstore-volume-logs:/var/log/eventstore
        - ./plugins:/usr/share/eventstore/plugins
